package com.flow.pharos.usecase

import android.content.Context
import android.net.Uri
import androidx.documentfile.provider.DocumentFile
import com.flow.pharos.core.llm.FilenameSanitizer
import com.flow.pharos.core.llm.JsonParser
import com.flow.pharos.core.model.entity.AnalysisEntity
import com.flow.pharos.core.storage.repository.AnalysisRepository
import com.flow.pharos.core.storage.repository.FileRepository
import com.flow.pharos.core.storage.repository.FolderRepository
import com.flow.pharos.core.storage.repository.ProjectRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.withContext
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

data class MasterfileProgress(val current: Int, val total: Int, val currentProjectName: String = "")
data class MasterfileResult(val filesWritten: Int, val errors: Int)

class MasterfileUseCase(
    private val context: Context,
    private val projectRepository: ProjectRepository,
    private val fileRepository: FileRepository,
    private val analysisRepository: AnalysisRepository,
    private val folderRepository: FolderRepository
) {
    private val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault())

    suspend fun updateMasterfiles(
        onProgress: suspend (MasterfileProgress) -> Unit
    ): MasterfileResult = withContext(Dispatchers.IO) {
        val folders = folderRepository.getAllFoldersList()
        if (folders.isEmpty()) throw IllegalStateException("No folder configured")
        val folder = folders.first()
        val treeUri = Uri.parse(folder.treeUri)
        val documentFolder = DocumentFile.fromTreeUri(context, treeUri)
            ?: throw IllegalStateException("Cannot access folder")

        val projects = projectRepository.getAllProjectsList()
        var filesWritten = 0; var errors = 0

        projects.forEachIndexed { index, project ->
            ensureActive()
            onProgress(MasterfileProgress(index + 1, projects.size, project.name))
            try {
                val files = projectRepository.getFilesForProjectList(project.id)
                val analyses = mutableListOf<Pair<String, AnalysisEntity>>()
                files.forEach { file ->
                    analysisRepository.getLatestAnalysisForFile(file.id)?.let { analyses.add(file.name to it) }
                }
                val content = buildMasterfileContent(project.name, project.description, analyses)
                val sanitizedName = FilenameSanitizer.sanitize(project.name)
                writeMasterfile(documentFolder, "PHAROS_MASTER_$sanitizedName.md", content)
                filesWritten++
            } catch (e: Exception) {
                if (e is kotlinx.coroutines.CancellationException) throw e
                errors++
            }
        }
        MasterfileResult(filesWritten, errors)
    }

    private fun buildMasterfileContent(
        projectName: String,
        description: String,
        analyses: List<Pair<String, AnalysisEntity>>
    ): String {
        val sb = StringBuilder()
        sb.appendLine("# $projectName"); sb.appendLine(); sb.appendLine(description); sb.appendLine()
        sb.appendLine("**Last updated:** ${dateFormat.format(Date())}"); sb.appendLine()
        sb.appendLine("## Assigned Files"); sb.appendLine()
        if (analyses.isEmpty()) {
            sb.appendLine("_No analyzed files assigned to this project._")
        } else {
            analyses.forEach { (fileName, analysis) ->
                sb.appendLine("### $fileName"); sb.appendLine()
                analysis.summary.split(". ").filter { it.isNotBlank() }.take(6).forEach { line ->
                    val cleaned = line.trim().removeSuffix(".")
                    if (cleaned.isNotBlank()) sb.appendLine("- $cleaned")
                }
                sb.appendLine()
                val topics = JsonParser.fromJsonArray(analysis.topics)
                if (topics.isNotEmpty()) {
                    sb.appendLine("**Topics:** ${topics.joinToString(", ")}"); sb.appendLine()
                }
            }
        }
        val allActionItems = analyses.flatMap { (_, a) -> JsonParser.fromJsonArray(a.actionItems) }.distinct()
        if (allActionItems.isNotEmpty()) {
            sb.appendLine("## Open Items"); sb.appendLine()
            allActionItems.forEach { sb.appendLine("- [ ] $it") }
            sb.appendLine()
        }
        sb.appendLine("---"); sb.appendLine("_Generated by Pharos_")
        return sb.toString()
    }

    private fun writeMasterfile(folder: DocumentFile, fileName: String, content: String) {
        val existing = folder.findFile(fileName)
        if (existing != null) {
            context.contentResolver.openOutputStream(existing.uri, "wt")?.use {
                it.write(content.toByteArray(Charsets.UTF_8))
            } ?: throw IllegalStateException("Cannot write to $fileName")
        } else {
            val newFile = folder.createFile("text/markdown", fileName)
                ?: throw IllegalStateException("Cannot create $fileName")
            context.contentResolver.openOutputStream(newFile.uri)?.use {
                it.write(content.toByteArray(Charsets.UTF_8))
            } ?: throw IllegalStateException("Cannot write to $fileName")
        }
    }
}
